defaults:
  - _self_
  - env: robosuite_3d

name: robosuite_square_pc
env_name: NutAssemblySquare
obs_keys:
- frontview_pc
- robot0_eye_in_hand_pc
- frontview_pc_mask
- robot0_eye_in_hand_pc_mask
- robot0_eef_pos
- robot0_eef_quat
- robot0_gripper_qpos
num_points: 512
bounding_boxes:
  frontview:
    lower_bound: [-0.5, -0.4, 1.0]
    upper_bound: [0.5, 2.0, 2.35]
  robot0_eye_in_hand:
    lower_bound: [-0.5, -0.5, 0.0]
    upper_bound: [0.5, 0.5, 0.5]
delta_action: false
max_episode_steps: 200
num_episodes: 40