defaults:
  - _self_
  - env: robosuite_3d

name: robosuite_can_pc
env_name: PickPlaceCan
obs_keys:
- agentview_pc
- robot0_eye_in_hand_pc
- agentview_pc_mask
- robot0_eye_in_hand_pc_mask
- robot0_eef_pos
- robot0_eef_quat
- robot0_gripper_qpos
num_points: 512
bounding_boxes:
  frontview:
    x: [-0.5, 0.5]
    y: [-0.2, 3]
    z: [0, 1.5]
  robot0_eye_in_hand:
    x: [-0.5, 0.5]
    y: [-0.5, 0.5]
    z: [0, 0.5]
max_episode_steps: 300
num_episodes: 20