defaults:
  - _self_
  - env: robosuite

name: robosuite_square_image
env_name: NutAssemblySquare
obs_keys:
- agentview_image
- robot0_eye_in_hand_image
- agentview_image_mask
- robot0_eye_in_hand_image_mask
- robot0_eef_pos
- robot0_eef_quat
- robot0_gripper_qpos
delta_action: false
max_episode_steps: 300
num_episodes: 100