defaults:
  - _self_
  - env: robosuite

name: robosuite_stack_image
env_name: Stack
obs_keys:
- agentview_image
- robot0_eye_in_hand_image
- agentview_image_mask
- robot0_eye_in_hand_image_mask
- robot0_eef_pos
- robot0_eef_quat
- robot0_gripper_qpos
delta_action: true
max_episode_steps: 200
num_episodes: 100