defaults:
  - _self_
  - env: robosuite_3d

name: robosuite_can_pc
env_name: PickPlaceCan
obs_keys:
- agentview_pc
- robot0_eye_in_hand_pc
- agentview_pc_mask
- robot0_eye_in_hand_pc_mask
- robot0_eef_pos
- robot0_eef_quat
- robot0_gripper_qpos
num_points: 512
bounding_boxes:
  agentview:
    lower_bound: [-0.5, -0.2, 0.0]
    upper_bound: [0.5, 3.0, 1.5]
  robot0_eye_in_hand:
    lower_bound: [-0.5, -0.5, 0.0]
    upper_bound: [0.5, 0.5, 0.5]
max_episode_steps: 200
num_episodes: 40